### ISSUE TITLE
Changing index of index.yml

### ISSUE THREAD

**Issue by y9c4lk** [cloudfoundry/java-buildpack-dependency-builder#30]
Hey! I'm a really big fan of this tool! I used the old version (using bundle) to make a copy to my server and automatically change all the index.yml.

Now, I've just tried the new version (using aws cli) and I've checked the first downloads to be sure it's working right but unfortunately it doesn't. I could not check if after downloading all the files it updates the content of the index because I ran out of space in disk. Does it changes when downloading process is finished?

Before creating a new VM I'd like to be sure that this tools stills enables changing the path to my server in the index automatically. Is it possible? 

Thanks in advance

**Comment by nebhale** [comment]
@y9c4lk What specifically wasn't being changed?

**Comment by nebhale** [comment]
Actually, [this](https://github.com/cloudfoundry/java-buildpack-dependency-builder/blob/master/replicate.sh#L54) probably answers your question.  The base URI replacement happens after a complete download.
