### ISSUE TITLE
index.yml replacement broken

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/java-buildpack-dependency-builder#32]
Perhaps caused by 78c1dbe39f997aa6a48d5ad58187e15218be8cb6

Still investigating.

**Comment by youngm** [comment]
Nevermind.  Found the problem.  Thanks.

**Comment by nebhale** [comment]
@youngm Can you elaborate (publicly or privately) on what the problem was.  I'd like to have some context if anyone else experiences it.

**Comment by youngm** [comment]
@nebhale I setup a cron on a server to sync with your public repo long ago.  I also setup the script to automatically git pull this repo.  Well, looks like a long time ago the git pull stopped working since my server was still using the old ruby sync code.  Needless to say the change in url broke the old ruby base url replace code.

Anyway, situation resolved.  I'll have to watch this repository more carefully in the future I guess.  Thanks. :)
