### ISSUE TITLE
No documentation on how to actually build the dependencies

### ISSUE THREAD

**Issue by jandubois** [cloudfoundry/java-buildpack-dependency-builder#33]
It looks like all the build scripts under `bin/` have been moved to some concourse pipeline setup, but there is no pointer to the pipeline definition.

I was hoping that there is still some mechanism to manually build dependencies locally for testing purposes, but can't figure out how to do it. I guess I could try playing with the latest versions of the build scripts, before they got deleted, but they may no longer work anyways, so this may be a waste of time.

**Comment by nebhale** [comment]
The pipeline definition isn't actually important as the scripts [aren't really pipelined together](https://java-experience.ci.springapps.io/teams/java-experience/pipelines/java-buildpack-dependency-builder).

Each script should be self-contained, [returning errors](https://github.com/cloudfoundry/java-buildpack-dependency-builder/blob/master/groovy.sh#L8) if any of the properties it expects to exist are not set.  To shortcut the trial and error required to find all of the parameters, the Concourse task definitions actually contain an [inventory of all parameters](https://github.com/cloudfoundry/java-buildpack-dependency-builder/blob/master/groovy.yml#L17-L23) required for a given script.  It also [specifies the docker image](https://github.com/cloudfoundry/java-buildpack-dependency-builder/blob/master/groovy.yml#L4-L8) that the script expects to run in, which will provide all of the tools and utilities required.

Is this explanation enough, or would you like something different or something more to help?

**Comment by jandubois** [comment]
> Is this explanation enough, or would you like something different or something more to help?

Thanks, that should be good enough. I guess I managed to confuse myself by starting off with the memory-calculator script and not understanding how it actually built the thing. I realize now that the script just copies pre-built binaries that have been built elsewhere, and the actual build task is in the java-buildpack-memory-calculator repo. I should have looked there first.

I'll re-open if I run into problems, but I think I should be good now.

**Comment by nebhale** [comment]
Great.  Just as an FYI, the only dependency actually build by the dependency builder (yeah, the naming is probably more at fault that you are), is OpenJDK.

**Comment by jandubois** [comment]
> the only dependency actually build by the dependency builder [...] is OpenJDK.

Yeah, I expected this repo to be for the java buildpack what [binary-builder](https://github.com/cloudfoundry/binary-builder) is for the other ones. So I was looking for the "recipes" to build dependencies, and all I found was commit 9f0125b, which says:

>   This change removes all existing code from repository as it migrates to
>    a Concourse-based implementation.

Which sent me on my quest to find the elusive pipeline repo, which (in my mind) would at least have hints to the location of the actual building recipes.

So maybe adding a paragraph to the README that this repo doesn't actually build most dependencies could be helpful to the next person trying to figure this out?

**Comment by nebhale** [comment]
@jandubois Sounds good.
