### ISSUE TITLE
YourKit download url doesn't match the regex

### ISSUE THREAD

**Issue by jimmykarily** [cloudfoundry/java-buildpack-dependency-builder#36]
It seems that the [download url](https://github.com/cloudfoundry/java-buildpack-dependency-builder/blob/master/resources/your-kit-resource/src/main/java/org/cloudfoundry/dependency/resource/yourkit/YourKitCheckAction.java#L60) used doesn't have links matching [the version regex](https://github.com/cloudfoundry/java-buildpack-dependency-builder/blob/master/resources/your-kit-resource/src/main/java/org/cloudfoundry/dependency/resource/yourkit/YourKitCheckAction.java#L36). Maybe the page changed recently. The only page that has the "old" style named link is [the archives page](https://www.yourkit.com/download/older.html) but that doesn't include the latest version.

The issue is that concourse can't find any versions for your-kit because of the above problem.

**Comment by nebhale** [comment]
Thanks for the tip off.  Some this can be a bit brittle.  I'll get the resource updated and all the missing versions published.

**Comment by nebhale** [comment]
[`2017.2.68` published](https://java-experience.ci.springapps.io/teams/java-experience/pipelines/java-buildpack-dependency-builder/jobs/your-kit/builds/20)
