### ISSUE TITLE
Bionic jvmkill is not an ELF file

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/java-buildpack-dependency-builder#37]
While trying to create an offline-buildpack against the cflinuxfs3 stack, I noticed that the jvmkill asset being pulled in that should be ELF libraries, is just text. Can this be corrected?

https://java-buildpack.cloudfoundry.org/jvmkill/bionic/x86_64/jvmkill-1.13.0_RELEASE.so

**Comment by nebhale** [comment]
Yep, new versions of `cargo` build a debug map with a very similar name and our [glob pattern](https://github.com/cloudfoundry/jvmkill/blob/master/ci/deploy.sh#L19) is randomly uploading one or the other.  Working on it now.

**Comment by nebhale** [comment]
Fixed as of version `1.16.0.RELEASE`.  Thanks for bringing this to our attention.

**Comment by sclevine** [comment]
@geofffranks Possibly worth mentioning, cflinuxfs3 is not stable yet. We plan to remove packages, and that may break apps at runtime (ie. apps could fail to start after the rootfs is updated, even without restaging them).

**Comment by geofffranks** [comment]
Good to know, I was just doing some experimentation with a Java app that claims its deps are less invasive on 18.04 than on 14.04.
